name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        For questions/troubleshooting, please use GitHub Discussions.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue clearly and what you expected to happen.
      placeholder: "When I... I expected... but instead..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the problem.
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs (backend/frontend) or attach screenshots.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Frontend
        - Backend
        - Both
        - Docs
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Release tag/commit SHA, or "main".
      placeholder: "v0.1.0" or "main" or commit SHA
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + browser (for frontend) and Node version (if known).
      placeholder: "macOS 14.2, Chrome 121, Node 20"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might help.
    validations:
      required: false
