name: Feature request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature.

        If you want to discuss the idea before filing an actionable request, GitHub Discussions is recommended.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "I want to... because..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds you considered.
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / requirements
      description: Any constraints, expected behavior, or acceptance criteria.
      placeholder: |
        - Must...
        - Should...
        - Nice to have...
    validations:
      required: false

  - type: dropdown
    id: willingness
    attributes:
      label: Are you willing to contribute a PR?
      options:
        - Yes
        - Maybe
        - No
    validations:
      required: false
